[theme]
base                     = "light"      # "light" ou "dark"
primaryColor             = "#1E90FF"    # azul de destaque
backgroundColor          = "#FFFFFF"    # fundo principal
secondaryBackgroundColor = "#E3F2FD"    # fundo de painéis / cards
textColor               = "#000000"     # texto principal
font                     = "sans serif"