[theme]
base="light"
primaryColor="#1E90FF"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"
font="sans serif"

[themeDark]
primaryColor="#1E90FF"
backgroundColor="#2D2D2D"
secondaryBackgroundColor="#444444"
textColor="#FFFFFF"